# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    asana_key: '%env(ASANA_KEY)%'
    workspace_id: '%env(WORKSPACE_ID)%'
    formation_project_id: '%env(FORMATION_PROJECT_ID)%'
    paca_project_id: '%env(PACA_PROJECT_ID)%'
    other_project_id: '%env(OTHER_PROJECT_ID)%'

    formation_email_receiver: '%env(FORMATION_EMAIL_RECEIVER)%'
    project_email_receiver: '%env(PROJECT_EMAIL_RECEIVER)%'

    upload_directory: '%kernel.project_dir%/public/uploads'
    images_news_directory: '%kernel.project_dir%/public/uploads/images/news'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'